#!/bin/bash

OUTPUTFILE=$1".367"

frequency367 $1 "frequencylistscript"
createcode367 "frequencylistscript" "codebookscript"
encode367 "codebookscript" $1 "compressedscript" 
cat "codebookscript" "compressedscript" > $OUTPUTFILE

